#!/usr/bin/env bash
# Rebuild and publish the GitHub Pages site.
#
# The site is a BUILD, assembled from two branches, so pushing to master or
# san-ramon does not update it on its own -- run this. That is the one cost of
# serving two cities from one repo, and it is why gh-pages carries a warning in
# its commit message rather than being editable by hand.
#
# Layout, and why:
#   /                 chooser page (lives in this script, below)
#   /app/             Los Angeles, from master, at the SAME paths Pages served
#                     when it was pointed at master -- so links already shared
#                     still resolve. Do not move this.
#   /sanramon/app/    San Ramon, from san-ramon
#
# Each app reads ../data/, so each city needs its data one level up from its
# app/. Only the three files an app actually fetches are copied; the pipeline's
# rasters, building footprints and CSVs are not part of the site.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT
cd "$REPO"

command -v git >/dev/null || { echo "git not found"; exit 1; }
git rev-parse --verify master   >/dev/null 2>&1 || { echo "no master branch";   exit 1; }
git rev-parse --verify san-ramon >/dev/null 2>&1 || { echo "no san-ramon branch"; exit 1; }

echo "building into $BUILD"
mkdir -p "$BUILD/data" "$BUILD/sanramon/data"

# --- Los Angeles (master) ---
git archive master app/ | tar -x -C "$BUILD"
for f in la.geojson centers.geojson boundary.geojson; do
  git show "master:data/$f" > "$BUILD/data/$f"
done

# --- San Ramon (san-ramon) ---
git archive san-ramon app/ | tar -x -C "$BUILD/sanramon"
for f in sanramon.geojson centers_sanramon.geojson boundary_sanramon.geojson; do
  git show "san-ramon:data/$f" > "$BUILD/sanramon/data/$f"
done

# .nojekyll: Pages runs Jekyll by default and Jekyll drops underscore-prefixed
# paths. Nothing here starts with one today; that is not a reason to find out.
touch "$BUILD/.nojekyll"
cp "$REPO/site/index.html" "$BUILD/index.html"

for f in index.html app/index.html sanramon/app/index.html \
         data/la.geojson sanramon/data/sanramon.geojson; do
  [ -s "$BUILD/$f" ] || { echo "MISSING or empty: $f"; exit 1; }
done

cd "$BUILD"
git init -q -b gh-pages
git remote add origin "$(git -C "$REPO" remote get-url origin)"
git add -A
git commit -q -m "Build: Los Angeles at /app/, San Ramon at /sanramon/app/

Generated by deploy.sh from master ($(git -C "$REPO" rev-parse --short master)) and
san-ramon ($(git -C "$REPO" rev-parse --short san-ramon)). Do not edit this branch
by hand -- the next deploy force-pushes over it."
git push -q --force origin gh-pages

echo
echo "pushed. Pages usually takes 1-2 minutes."
echo "  https://advikar.github.io/coolequity/"
echo "  https://advikar.github.io/coolequity/app/           (Los Angeles)"
echo "  https://advikar.github.io/coolequity/sanramon/app/  (San Ramon)"
